### ISSUE TITLE
Replace contents of this site with redirect to blog category

### ISSUE THREAD

**Issue by jgmize** [mozilla/surveillance.mozilla.org#10]
https://blog.mozilla.org/netpolicy/category/surveillance/

This site is currently backed by s3: https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

Afterwards, we can archive this repo: https://help.github.com/articles/about-archiving-repositories/

**Comment by jgmize** [comment]
thoughts @bensternthal?

**Comment by bensternthal** [comment]
checking with JKW

**Comment by bensternthal** [comment]
jkw requests we leave the site as is.
