### ISSUE TITLE
Unable to permalink to "Surveillance Principles" page

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/surveillance.mozilla.org#4]
When attempting to share the "Surveillance Principles" page with a friend, I was unable to generate a permalink directly to it. The address bar does not include any # or #! tokens indicating the "current page", so no matter where I go on the site, I can only link them to the home page and try to fit instructions for "click here, click there" into 140 characters.

**Comment by joshrounsville** [comment]
Can you clarify this one for me?

The Surveillance Principles page lives at the root of the site (https://surveillance.mozilla.org/) and linking to it shouldn't cause any issue.

**Comment by floatingatoll** [comment]
Huh. I must have gotten confused. Alright, works for me, thanks!
