### ISSUE TITLE
Creative Commons LICENSE file missing from this repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/surveillance.mozilla.org#5]
Per the footer of the site, "Content available under a Creative Commons license.", however, there is no LICENSE file in this repository reflecting that.

**Comment by joshrounsville** [comment]
Can we link to the license that lives on Mozilla.org (https://www.mozilla.org/en-US/foundation/licensing/website-content/) or do we need a page specific to this site?

**Comment by joshrounsville** [comment]
@floatingatoll ^

**Comment by floatingatoll** [comment]
Generally, the github repository needs to include a file called "LICENSE" at the root of the repository. It doesn't have to be published to the live website, it just has to be in the repository.

**Comment by joshrounsville** [comment]
Got it. Thanks!

**Comment by floatingatoll** [comment]
So, looking at that site. Hm. Technically, the LICENSE file should be a plain copy of CC-whatever-3.0 that we're using. BUT. If you were to say:

"This repository is licensed under the terms described at [link-to-/licensing/website-content/] under CC-whatever-3.0, as follows: \n\n", then that would cover all the bases nicely.

**Comment by joshrounsville** [comment]
@floatingatoll 

I ended up adding the LICENSE file to the repo and linking to the /foundation/licensing/website-content/ page from the site itself (not yet live) which seems to be the strategy here: 
https://github.com/mozilla/petitions.mozilla.org

Does this work?

**Comment by floatingatoll** [comment]
Sure! Really, it's all about _having_ a LICENSE file. Anything beyond that is icing.
