### ISSUE TITLE
Implement missing HTTP headers

### ISSUE THREAD

**Issue by april** [mozilla/surveillance.mozilla.org#7]
Hello hello!  I'm April from the #infosec team, just stopping in to help y'all configure your new site to meet the new Mozilla Web Security standards:

https://wiki.mozilla.org/Security/Guidelines/Web_Security

I know that there's nothing sensitive on the site, but I figure that if we're going to have a site about surveillance and security, then we out to do it right ourselves.  :)  So here's the headers we need to add:

```
Content-Security-Policy: default-src 'none'; font-src http://fonts.gstatic.com; img-src 'self'; script-src 'self' 'sha256-DXaGZ8ElJMOIJaDhLXLCGcVTScuVHzZp24WJyGI7RPs=' https://www.google-analytics.com data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

Make sure to test CSP; note that the sha256- is for the inline google analytics thing, and could be removed if we moved it into a separate script.  I tested it by poking around on the site and everything seemed to work okay.

Thanks, and please let me know if I can help in any way.  :)

**Comment by april** [comment]
I hear you're using nginx!  It's pretty easy to add a header.  Just put it inside your server {} block like so:

```
add_header Strict-Transport-Security "max-age=31536000";
```

(and so on)

**Comment by joshrounsville** [comment]
@marumari 

Hi April - 

Could you take a look at the nginx.conf file and verify that the headers have been added correctly? I'm no nginx expert and want to make sure it's correct. Thanks!

**Comment by bensternthal** [comment]
This is now live, headers look to be set correctly.

![screen shot 2016-03-08 at 2 19 21 pm](https://cloud.githubusercontent.com/assets/198507/13618416/d657e212-e538-11e5-90c3-ac865d338be6.png)

**Comment by april** [comment]
Oh weird, for some reason github didn't send me any notifications.  Grr!

Here are the results from our scanner:

```
$ httpobs surveillance.mozilla.org
Score: 45 [D+]
Modifiers:
    [ -10] Contribute.json file missing from root of website
    [ -20] X-Frame-Options (XFO) header cannot be recognized
    [ -25] Content Security Policy (CSP) header missing
```

Looks like nginx.conf has a mistake:

`add_header X-Frame-Options: DENY`;

Should be:

`add_header X-Frame-Options DENY`;

Otherwise, looks like a great start, sans CSP.  :)

**Comment by bensternthal** [comment]
This is live, please re-run your tests.

**Comment by april** [comment]
Looking much better!

```
 ❯ httpobs -r surveillance.mozilla.org                                                                       [17:07:11]
Score: 65 [B-]
Modifiers:
    [ -10] Contribute.json file missing from root of website
    [ -25] Content Security Policy (CSP) header missing
```
