### ISSUE TITLE
Remove git repo data from website

### ISSUE THREAD

**Issue by psiinon** [mozilla/surveillance.mozilla.org#9]
The git repo data is being exposed via https://surveillance.mozilla.org/.git/ as per https://bugzilla.mozilla.org/show_bug.cgi?id=1479976
As the repo is public its not really a security risk, but it will be reported to us as such, and in any case its not really best practice.

**Comment by jgmize** [comment]
Thanks, I've deleted the git repo data from the s3 bucket backing this site.
